### ISSUE TITLE
Precompute_BM function error?

### ISSUE THREAD

**Issue by qjyun99** [gfacciol/bm3d#10]
Dear    
Is there any error in line 1375?  
    for (int di = - (int) nHW; di < 0; di++)
###                    **// if (sum_table[-dj + nHW + (-di) * Ns][k_r] < threshold) //should be
 **if (sum_table[-dj + nHW + (-di) * Ns][k_r + di * width + dj] < threshold)****
                        table_distance.push_back(make_pair(
                                    sum_table[-dj + nHW + (-di) * Ns][k_r + di * width + dj]
                                  , k_r + di * width + dj));

**Comment by tehret** [comment]
Thanks for discovering this bug. We fixed it.
