### ISSUE TITLE
RAM problem with large images

### ISSUE THREAD

**Issue by valerioroscani** [gfacciol/bm3d#11]
I work with large 32 bits floating point TIFF. The code works great with 1000x1000 pixels images, while with larger ones (e.g. 5000x5000, 10000x10000) it uses the 99%-100% of the RAM (32GB) making the entire system unresponsive for several hours (16+ hours) and in the end terminating the  process uncompleted. 
I use other noise reduction algorithms on such images, but it is the first time I've this kind of problem. 
Any suggestion or indication? Perhaps some parameter to set or similar? Is the code suitable for images larger than 1000x1000?
Thank you.

**Comment by gfacciol** [comment]
Hi,
The best would be to cut the images in smaller overlapping tiles. The
result would not be affected.
The reason is that the code is pre-allocating all the groups of patches for
the image.
best
-
