### ISSUE TITLE
Saving as JPG results in image that can not be opened

### ISSUE THREAD

**Issue by timmeinhardt** [gfacciol/bm3d#2]
The `./bm3d` executable seems to have a problem with saving an image in the JPG format. I tried to denoise [this image](https://boofcv.org/images/1/18/Example_lena_denoise_noisy.jpg) which worked only if I set the output filename to `*.png` but not `*.jpg`. The denoising seems to work in both cases but for the latter the saved image can not be opened.

**Comment by gfacciol** [comment]
Sorry about that, writing JPG files is not supported by the IO library I use.
PNG should be used for 8bit output, and TIFF  for 16+bits or floating point. 
The fallback format is PNM so your output is probably a PPM or PGM.  
To view images regardless of their format (especially fancy float TIFFSs) you can use : 
https://github.com/gfacciol/pvflip   or   ImageJ.

**Comment by luczeng** [comment]
Hey, I'm trying to save the image as TIFF but it doesn't seem to be working. Inputing the images as TIFF and saving them as png is working though.
Should I modify your code or is there a work around ?
Thanks

**Comment by gfacciol** [comment]
The TIFF produced by the program should be a 32 bits floating point TIFF.
You should be able to verify it by running:    
> tiffinfo output.tif 
If it's not a TIFF, then  
>  identify output.tif
should be able to find out the format. 

This format (32bit float) is not very popular with the usual image viewers.
Matlab can http://linuxtoosx.blogspot.fr/2012/05/reading-floating-point-multi-channel.html
Where are you reading the image?

**Comment by luczeng** [comment]
Yeah I got it. I was using ubuntu embedded image viewer and was seeing a blank screen, so I thought the program had failed. I can open the image with RawTherapee.
Any reason to save TIFFs as 32bits floats ? It's surprising as my input has 8 bits. Probably gonna convert it to 8 bits one way or the other.
Thanks

**Comment by gfacciol** [comment]
The reason we use 32 bits floats is that internally all the processing is done at that precision, 
and the implementation is agnostic to the dynamic range of the input image. 
To export a "classic" 8-bits file you can set the extension of the output file to    output.png 
that's a very common lossless format that all viewers can see.
